### ISSUE TITLE
알림센터 LITE 오류에 대한 문의드립니다.

### ISSUE THREAD

**Issue by kskyung4u** [xe-public/xe-module-ncenterlite#101]
![screenshot 58](https://cloud.githubusercontent.com/assets/10719591/10715724/7a457938-7b63-11e5-9eb7-e0ab2b790fb5.png)

알림LITE 그동안 잘 써왔는데 이번에 새롭게 사이트 작업을 하다가 한 번도 겪지 못했던, 문제가 발생해서 이슈에 남깁니다. 위의 스크린샷에서 처럼 알림에 요약글을 클릭하면 잘못된 요청 오류창이 뜹니다.

앞 전에 저랑 동일한 증상으로 이슈 올리신 글을 보고 커뮤니케이션을 키고, 쪽지 알림을 OFF 하고 모든 페이지에서 활성화 되도록 하였음에도 제대로 작동하지 않고 있습니다. 이리저리 살펴봐도 어디서 문제인 알 수가 없어서 도움 요청드립니다. 감사합니다.

http://www.smarp.kr/index.php?act=procNcenterliteRedirect&notify=d36394f4b51d389b32f6d900b346dd19&url=%2F

**Comment by qw5414** [comment]
https://github.com/xe-public/xe-module-ncenterlite/commit/b0b603941fbf80489212f7560fb8bad5330fbab3 #98

**Comment by qw5414** [comment]
이미 고쳐놨습니다. 다음 패치버전때 해결됩니다.. 아직 공홈에서 받아들여지지 않아 기다리고 있습니다 .
