### ISSUE TITLE
회원정보보기 [act=dispMemberInfo] 에서 내 알림설정을 누르면 상단 리스트가 사라짐

### ISSUE THREAD

**Issue by hjhj3686** [xe-public/xe-module-ncenterlite#105]
![test](https://cloud.githubusercontent.com/assets/1341628/12637010/5dad860a-c5d5-11e5-8dd4-d59d428ba756.PNG)
![test2](https://cloud.githubusercontent.com/assets/1341628/12637013/61a4a9c8-c5d5-11e5-9f98-85c10e6b7b46.PNG)
그림 참조

**Comment by qw5414** [comment]
사용하시는 스킨에 따라 다릅니다.

**Comment by qw5414** [comment]
사용하시는 스킨에서,
userconfig.html 파일 최상단
```html
<load target="../../../member/skins/default/css/member.css" />
<include target="../../../member/skins/default/common_header.html" />```
코드 삽입
