### ISSUE TITLE
인덱스가 누락되어 댓글 삭제시 시간이 오래 걸림

### ISSUE THREAD

**Issue by kijin** [xe-public/xe-module-ncenterlite#106]
댓글이 많이 달린 글을 삭제하면 각각의 댓글을 삭제하는 과정에서 알림센터 트리거가 호출되는데, 여기서 사용하는 `deleteNotifyBySrl` 쿼리가 참조하는 `srl`, `target_srl` 컬럼에 인덱스가 없습니다.

그래서 알림이 많이 쌓인 상태에서 댓글이 많이 달린 글을 삭제하면 시간이 아주 오래 걸리고, 심지어 타임아웃이 발생하기도 합니다.

그 밖에도 `target_p_srl`, `target_member_srl` 등 쿼리에서 검색 조건으로 사용할 가능성이 있는 컬럼에는 모두 인덱스를 걸어두는 것이 좋겠습니다.

**Comment by bjrambo** [comment]
일딴 추가해드렸습니다. 몇가지 더 필요하신거 있으면 남겨주세요 댓글로 ~

**Comment by kijin** [comment]
인덱스 관련 이슈 추가...

`notify` 컬럼은 이미 primary key로 지정되어 있는데 불필요한 인덱스를 또 생성하고 있네요.

**Comment by bjrambo** [comment]
@kijin 헛 그렇군요 ;ㅁ;
 그렇게 설정되어잇으면 인덱스는 필요없게 되나요?@_@?

**Comment by kijin** [comment]
네, primary key는 자동으로 인덱스가 걸립니다.

**Comment by bjrambo** [comment]
@kijin 근데 미리 생성된 디비에 대해서도 index가 없다고 뜰수있나요? 최근에 추가한거라 혹시 index검사에서 false뜨지 않앗을까 하는거같은기분도 들긴하지만..(뭐 지워주면되고요 ㅋ)

**Comment by kijin** [comment]
XE에서는 인덱스 이름을 기준으로 인덱스 존재 여부를 판단하기 때문에, primary key로 자동 생성된 인덱스는 존재하지 않는 것으로 취급합니다.

**Comment by bjrambo** [comment]
@kijin 저런 그렇군요 =_= 나쁜친구닷!(응?)

**Comment by bjrambo** [comment]
```php
	function isIndexExists($table_name, $index_name)
	{
		$query = sprintf("select sysindexes.name as name from sysindexes, sysobjects where sysobjects.name = '%s%s' and sysobjects.id = sysindexes.id and sysindexes.name = '%s'", $this->prefix, $table_name, $index_name);
		$result = $this->_query($query);
		if($this->isError())
		{
			return;
		}
		$tmp = $this->_fetch($result);
		if(!$tmp->name)
		{
			return false;
		}
		return true;
	}
```
여기에 한번더 조건을 입력할 수 있나요??

**Comment by kijin** [comment]
코어는 건드릴 필요 없고, 그냥 `idx_notify` 인덱스를 체크하고 생성하는 코드만 지워주면 될 것 같습니다. 이미 만들어진 경우 삭제해 준다면 더 좋겠지만, DB 종류에 따라 부작용이 있을 수 있으니 주의해야겠고요.

**Comment by bjrambo** [comment]
@kijin 음 제말은.. 혹시 이와같은 경우가 또 발생을 대비에서 한번 더 검사처리할 수 잇으면 좋지 않을까 해서요.

처음 비교했을때 한번 넘어가고, 해당 인덱스가 없을경우 바로 true으로 리턴이 되는게 아니라 프리마리(?)키로 다시한번 더 검사해서 이게 맞다면 true으로 돌리게 하는거죠. 그러면 다른 서드파티에서도 이와같은 작업이 중복으로 이루어지지 않을 수 있지 않을까 해요.

**Comment by kijin** [comment]
그건 코어 쪽에서 지원해 줘야 하는 것이므로 이 이슈의 범위는 벗어나는 것 같네요. (여긴 알림센터 깃허브이지 라이믹스 깃허브가 아닙니다 ㅋㅋ)

**Comment by bjrambo** [comment]
@kijin 넵 일딴 이건 처리해둘께요 저녁쯤..ㅠㅠ

**Comment by bjrambo** [comment]
할일재조기 Rhymix에 넣고왔음 (도망)
https://github.com/rhymix/rhymix/issues/533

**Comment by bjrambo** [comment]
아 근데 노피티는 제가 일시적으로 추가했던거였나요? 왜있지 ㄷㄷ

**Comment by bjrambo** [comment]
fix in ac4fb8f

**Comment by bjrambo** [comment]
추가적인 디비 칼럼 문제는 새로운 이슈에서 처리해봅시다 아직은 자주쓰일 인덱스가 생각나질 않는것 같아서..ㅎ)
