### ISSUE TITLE
Ajax 기능이랑 사용하면 문제 발생합니다

### ISSUE THREAD

**Issue by perzona420** [xe-public/xe-module-ncenterlite#107]
@bjrambo 디버그 결과 오류가 납니다. 특히 Ajax기능이랑 사용하면 문제가 발생합니다.
전송 후 에디터에 아직도 글이 남아 있거나 클릭이 안되거나(?)하는 현상입니다.
나름 심각한 오류랍니다 OTZ..

AJAX : board.procBoardInsertComment
Errors (3)
01. Warning: Creating default object from empty value
modules/ncenterlite/ncenterlite.model.php:293
modules/ncenterlite/ncenterlite.controller.php:173
classes/module/ModuleHandler.class.php:1208
modules/comment/comment.controller.php:583
modules/board/board.controller.php:372
classes/module/ModuleObject.class.php:438
classes/module/ModuleHandler.class.php:744
index.php:58
02. Warning: in_array() expects parameter 2 to be array, null given
modules/ncenterlite/ncenterlite.controller.php:178
classes/module/ModuleHandler.class.php:1208
modules/comment/comment.controller.php:583
modules/board/board.controller.php:372
classes/module/ModuleObject.class.php:438
classes/module/ModuleHandler.class.php:744
index.php:58
03. Warning: in_array() expects parameter 2 to be array, null given
modules/ncenterlite/ncenterlite.controller.php:178
classes/module/ModuleHandler.class.php:1208
modules/comment/comment.controller.php:583
modules/board/board.controller.php:372
classes/module/ModuleObject.class.php:438
classes/module/ModuleHandler.class.php:744
index.php:58

원하시면 해당 증상이 발생되는 사이트 알려드릴게요~

**Comment by bjrambo** [comment]
develop으로 다시 한번 테스트 해보세요.

배포버전과 지금 현재 깃허브 버전과 많이 차이 잇습니다.

DB테이블에 인덱스 추가 하는기능으로 DB칼럼 업데이트 필요합니다.(관리자페이지에서 업데이트 절차따르면끗)

**Comment by perzona420** [comment]
@bjrambo 오오, 정상적으로 뜨네요 :+1:
