### ISSUE TITLE
회원가입시 알림 기능

### ISSUE THREAD

**Issue by eondcom** [xe-public/xe-module-ncenterlite#108]
https://ncenter.userecho.com/topics/17-/

예전 판매되던 프로버전에는 있는 기능이긴 한데,
프로버전을 더 이상 구할 수 있는 건 아닌거 같아서 
추가 기능 요청드립니다.

https://www.xpressengine.com/index.php?mid=download&package_id=18335281

이 자료에는 해당 기능이 있는데 
알림센터 등 회원가입 관련 애드온과 같이 사용하려니 정상적으로 동작하지 않는 것 같아서요;

**Comment by bjrambo** [comment]
갠적으로 따로 구현한적있어서 가능은 할것 같네요.

**Comment by bjrambo** [comment]
현재는 라이믹스 -> 알림센터 먹는 작업이 있다보니. 조금 걸릴듯 해요.
