### ISSUE TITLE
PHP 7 환경에서 클릭불가현상 발생합니다

### ISSUE THREAD

**Issue by raildriver** [xe-public/xe-module-ncenterlite#109]
PHP 7  에 XE최신버전환경에서 설치했는데

알림은 뜨는데 클릭불가 현상이 납니다

**Comment by bjrambo** [comment]
일부 레이아웃에 따라 클릭이 어려울수 있습니다.
해당 부분은, 스킨을 하단스킨으로 선택해보시는등의 테스트를 해보시기 바랍니다.(php7환경에서도 잘사용되는구간 많네요..)

**Comment by raildriver** [comment]
해결됐습니다!
Xdetion 스킨에서 알림센터 스킨 설정에서 z-index를 1000000 정도로 높게 설정하니 해결됐네요
다른분들도 참고하시길 바랍니다
