### ISSUE TITLE
xe 알림센터 lite 업그레이드 이후 본인글의 댓글에도 알림이 뜹니다.

### ISSUE THREAD

**Issue by GuSeoJun** [xe-public/xe-module-ncenterlite#112]
본인 글의 댓글에는 알림이 뜰 필요가 없는데 알림이 뜨네요.

xe 알림센터에서는 수정하는 곳이 없는데.... 어디를 손봐야 할까요??

**Comment by bjrambo** [comment]
관리자에게 댓글 알림을 사용여부확인해주시고 관리자계정에만 나타나는지만 확인해주세요.
