### ISSUE TITLE
쪽지 읽을 경우 알림 삭제 기능 오동작 ?

### ISSUE THREAD

**Issue by wookho** [xe-public/xe-module-ncenterlite#124]
제가 이전에 해당 기능이 없는 줄 알고 해당 기능을 요청하는 이슈를 남겼습니다.
그런데 오늘 코드를 보다 보니 

https://github.com/xe-public/xe-module-ncenterlite/blob/develop/ncenterlite.controller.php#L582-L601

이 코드가 관리자페이지에서 옵션에는 없지만 쪽지를 읽을 경우 알림을 삭제해주는 기능인 듯 합니다.

그런데 실제로는 쪽지를 읽어도 알림이 삭제되지 않습니다. 저는 기능자체가 없는 줄 알고 기능추가 이슈로 이전에 등록을 했는데요.

코드는 들어가 있는데 실제 동작을 하지 않고 있습니다. 쪽지도 읽게 되면 삭제되게 해주세요.

**Comment by bjrambo** [comment]
해당 오류가 message_srl 이 도착하는 부분과 보내는 부분 두곳이 나눠져있다보니 이부분의 관리가 달라져서 생기는 문제같아요.

따라서 기록할 때 도착하는 고유번호를 통해서 검색하도록 수정하였습니다.

기존알림의 경우 동작하지 않으니 사용자들에게 삭제할 수 있도록 안내해주시는 것이 좋겠습니다.
