### ISSUE TITLE
알림센터 위젯 필요

### ISSUE THREAD

**Issue by kaijess** [xe-public/xe-module-ncenterlite#74]
네이버를 예로 들면 알림 아이콘에 N표시 가 되어 알림이 왔다는걸 알려줍니다.
또한 그걸 눌렀을시에 레이어가 떠서 리스트를 보여주구요

현재 알림센터는 알림이 있을때만 띄워주지만 레이아웃에 심을수 있도록 하는것도 좋다고 봅니다.

**Comment by qw5414** [comment]
이건 모듈과는 별개이므로 이슈닫을께요 ~
