### ISSUE TITLE
스킨 파일 중 NotifyList.html 에서 잘못된 css 파일 로딩

### ISSUE THREAD

**Issue by devdho** [xe-public/xe-module-ncenterlite#79]
스킨 파일 중 NotifyList.html 에서 notify.css 를 로드하고 있는데 경로가 잘못되었거나 사용되지 않는 파일 같습니다.

```html
<load target="css/notify.css" />
```

**Comment by misol** [comment]
https://github.com/xe-public/xe-module-ncenterlite/pull/93 에서 한꺼번에 해결했습니다.
