### ISSUE TITLE
XE Core 1.8.5, XEDTION 레이아웃과의 호환 문제

### ISSUE THREAD

**Issue by Altberta** [xe-public/xe-module-ncenterlite#84]
XE Core 1.8.5 버전으로 업데이트 후, 알림을 클릭하였을 시 알림이 확인되지 않고, 링크 뒤에 # 표시만 붙어버리는 문제가 발생하고 있습니다. 일단 1.8.3 버전으로 롤백하여 이 문제가 해결된 상태이나, 확인이 필요할 것 같습니다.

그리고, XE 1.8 버전의 기본 레이아웃인 XEDTION 사용 시, '서브형' 레이아웃에서 서브메뉴와 알림끼리 충돌이 있어서 스크롤을 살짝 내려준 상태에서만 알림 클릭이 가능한 문제가 있습니다. 또한, 스크롤을 아예 내려주지 않은 상태에서는 알림이 레이아웃을 무시하고 서브메뉴 위에 바로 덮이는 형태로 나타나게 됩니다.

**Comment by qw5414** [comment]
@Altberta 오른쪽 하단 스킨을 사용해보시길 권장드려요!
