### ISSUE TITLE
새로운 방식의 새글알림추가.

### ISSUE THREAD

**Issue by qw5414** [xe-public/xe-module-ncenterlite#85]
새글 알림을 다른 디비에 추가, (1개)
회원의 경우 읽음표시가 있을경우, 알림목록에서 삭제,

새글알림을 읽은 회원은 다른 DB에 document_srl, member_srl, module_srl, 기타등등을 기록.

새글알림방식.

InsertDocumentTrigger를 통해서, 새로 생성한 테이블에 저장.(저장은 1개만 합니다.)

새로생성한 테이블은 모든 회원이 읽을 수 있어야 합니다. (따로 읽는 사람이 정해져있지 않기 때문)

그래서 디비 정보는
글번호, 글쓴이회원정보, 글 제목, 글 내용 으로 간추려집니다.

그리고 작동방식은

기존 알림센터 디비와 함께 융화되어서 사용되어야 합니다.

EX

~회원이 ~글을 남겼습니다.
~회원이 ~글에 댓글을 남겼습니다
~회원이 ~글을 남겼습니다.

이런식으로 원래 기존에 쓰던 댓글, 언급,쪽지 알림과 함께 새글알림이 다른디비에 있더라도 포함되어서 보여지도록 해야합니다. (보여주는 타겟이 없음..)

새글 알림의 읽음표기를 제어하기 위해서 마련되는 것은

새로운 디비를 개설합니다.
document_srl
member_srl
read 

이렇게 저장합니다. read엔 Y, N으로만 표기합니다.

그래서 read와 document 을 인식하여 Y가 된 게시물의 경우 자신의 알림목록에서 띄우지 않습니다.

**Comment by qw5414** [comment]
@misol 혹시 3개의 다른테이블의 내용을 하나의 쿼리 xml으로 같이 불러올 수 있나요?
그것도 regdate시간에 맞게, 순서 맞춰서 

하나는테이블은 그냥 하나의 데이터를 불러오고, 새글은 하나의 디비만 입력하고, 접속 후 클릭하는 액션에서 member_srl과 "Y or N"을 기록하는 디비 이렇게 3개 같이 해서 새글은 마지막 member_srl 과 Y 이런것들을 기록하는 두개를 합쳐 보여주는 방식.. 이런형태로 가고싶은데..흐음..ㅠ

**Comment by qw5414** [comment]
음.. 예를 들면..
1번 테이블 -> 원래쓰던 알림센터 테이블
2번 테이블 -> 새글 알림을 알릴 하나의 테이블
3번 테이블 -> 새글 알림을 읽은 여부 확인하는 테이블 (2번 테이블과 연동되어 읽음 안읽음을 인식시킴)

**Comment by misol** [comment]
@qw5414 어떤 쿼리를 쓰시려는건지 모르겠는데.. 여러 테이블에 걸친 select 는 가능해요.

적절한 예시인지 모르겠지만, `./member/queries/getMemberGroup.xml` 의 내용을 첨부합니다.

```xml
<query id="getMembersGroup" action="select">
    <tables>
        <table name="member_group" alias="a" />
        <table name="member_group_member" alias="b" />
    </tables>
    <columns>
        <column name="a.group_srl" alias="group_srl" />
        <column name="b.member_srl" alias="member_srl" />
        <column name="b.regdate" alias="regdate" />
    </columns>
    <conditions>
        <condition operation="in" column="b.member_srl" var="member_srl" filter="number" notnull="notnull" />
        <condition operation="equal" column="b.group_srl" default="a.group_srl" pipe="and" />
        <condition operation="equal" column="a.site_srl" var="site_srl" pipe="and" />
    </conditions>
</query>
```

**Comment by qw5414** [comment]
@misol 원래 베이스는 1번 테이블을 쓰고(이는 2,3 번의 영향을 절대 받지 않음) 2번과 3번의 테이블중 2번의 테이블은 1번과 비슷한 포맷을 가지고요, 3번은 맴버가 읽엇다 , 안읽었다를 읽어들여 2번과 1번을 함께 뛰우는 방식입니다.

**Comment by misol** [comment]
2, 3 번은 새로 생길 테이블인가요? 1번 테이블의 컬럼을 추가한다든지 하는 식으로는 구현이 불가능한가요?

**Comment by qw5414** [comment]
2번 3번은 새로생길 테이블이고, ...
1번테이블에 칼럼을 추가하는 방향도 생각해봤지만, 새글알림의 경우 여러회원에게 모두 뛰우기 위해서는 하나씩만 입력된걸 여러사람에게 같이 보여주는 방법이 이게 재일 낫다고 판단되어서요..
(즉, 새글 하나에 디비 입력은 한번이 끝이어야 합니다.)

**Comment by misol** [comment]
실험은 안해봤는데..

```xml
<query id="getMembersGroup" action="select">
    <tables>
        <table name="ncenterlite_table_b" alias="b" />
        <table name="ncenterlite_table_c" alias="c" />
    </tables>
    <columns>
        <column name="b.target_item_srl" alias="target_item_srl" />
        <column name="c.member_srl" alias="member_srl" />
    </columns>
    <conditions>
        <condition operation="in" column="c.member_srl" var="member_srl" filter="number" notnull="notnull" />
        <condition operation="equal" column="b.target_item_srl" default="c.target_item_srl" pipe="and" />
        <condition operation="equal" column="b.site_srl" var="site_srl" pipe="and" />
    </conditions>
</query>
```

**Comment by misol** [comment]
제가 만드는게 아니라서 테스트 해보면서 쿼리가 어떻게 날아가나 보기 전에는 장담을 못하겠어요 ㅠㅠ
XML 쿼리 만져보기 시작한게 얼마 안되어서.

**Comment by qw5414** [comment]
음! 대충 새글에 대한 쿼리나 그런거 만들어서 넣어볼께요 !

**Comment by qw5414** [comment]
@misol https://github.com/xe-public/xe-module-ncenterlite/tree/newDocument 현재 이게 새로운글 추가한 부분입니다.
새로운글에 추가되면 방금 추가한 디비의 글이 나타나는데 여기서 먼저 필요한건 원래 쓰던 알림센터 DB와 현재 추가된 디비가 잘융화되어서 순서를 정하고 같이 떠야하는게 1차 목표입니다.

**Comment by misol** [comment]
문서 모듈의 getDocumentList.xml 을 참고할만 한 것 같아요.
```xml
    <navigation>
        <index var="sort_index" default="list_order" order="order_type" />
        <list_count var="list_count" default="20" />
        <page_count var="page_count" default="10" />
        <page var="page" default="1" />
    </navigation>
```
라는 부분이 있는데, `<index var="sort_index" default="regdate" order="order_type" />` 정도로 하면 되지 않을까요? order_type 에는

```php
		// Check the target and sequence alignment
		$orderType = array('desc' => 1, 'asc' => 1);
		if(!isset($orderType[$args->order_type])) $args->order_type = 'asc';
```
와 같은 구문으로 들어갑니다.

**Comment by misol** [comment]
둘을 합하면
```xml
<query id="getMembersGroup" action="select">
    <tables>
        <table name="ncenterlite_table_b" alias="b" />
        <table name="ncenterlite_table_c" alias="c" />
    </tables>
    <columns>
        <column name="b.target_item_srl" alias="target_item_srl" />
        <column name="c.member_srl" alias="member_srl" />
    </columns>
    <conditions>
        <condition operation="in" column="c.member_srl" var="member_srl" filter="number" notnull="notnull" />
        <condition operation="equal" column="b.target_item_srl" default="c.target_item_srl" pipe="and" />
        <condition operation="equal" column="b.site_srl" var="site_srl" pipe="and" />
    </conditions>
    <navigation>
        <index var="sort_index" default="regdate" order="order_type" />
        <list_count var="list_count" default="20" />
        <page_count var="page_count" default="10" />
        <page var="page" default="1" />
    </navigation>
</query>
```
이런식?

**Comment by qw5414** [comment]
target_item_srl 은 어떤?

**Comment by misol** [comment]
newdoc.xml 에서 document_srl 와 비슷한 것을 생각하고 써본 변수에요.
member_srl 은 target_member_srl 이에요

**Comment by qw5414** [comment]
@misol newdoc 에서는 모든회원을 표기 하기 위한 수단입니다.

**Comment by misol** [comment]
@qw5414 어떤 구상을 하고 계신지.. 지금 밤이라 그런지 머리에 잘 안 그려져서 이 이상은 도움이 되지 못할 것 같습니다.

**Comment by qw5414** [comment]
@misol 즉 newdoc에 들어간 member_srl 은 글적은 사람을 인식하기 때문에, 따로 알림을 봐야하는 회원을 따로 두지 않습니다.
일반적인 알림센터의 member_srl 은 알림을 받을 사람을 인식하고 있습니다.

**Comment by qw5414** [comment]
알림센터모듈의 공식적으로.. 
`target_member~~` -> 알림을 유발시킨사람(글쓴이, 댓글쓴사람)
`member_srl` -> 그 알림을 받고 있는 당사자

**Comment by qw5414** [comment]
@misol 부족한 설명부분을 게시물 수정을 통해서 추가하였습니다.
