### ISSUE TITLE
알림센터로 새글 알림 오면 406에러나네요.

### ISSUE THREAD

**Issue by ppleo** [xe-public/xe-module-ncenterlite#86]
modsecurity  정책중

SecRule REQUEST_URI "\.php" "chain, msg:'PHP Injection Attacks'"
     72 SecRule REQUEST_URI "(dir|page|)" chain
     73 SecRule REQUEST_URI "=(http|https|ftp)\:/"

걸려서 댓글 알림 창을 클릭하면 406 에러가 나오네요. 혹시 저 같은 경우가 있으신지요??

저같은 경우는 modsecurity 가 인젝션 공격이라고 해서 차단해 버리네요....ㅡㅡ;;쩜..

문제 되는 부분을 보안 정책의 문제가 있는 부분을 삭제하니 아파치가 안 살아나네요..

다른 분들은 문제가 없으신지요??

**Comment by qw5414** [comment]
알림센터의 URL클릭시, 리다이렉팅 부분을 사용하고 있습니다..;ㅁ; 해당 부분에서 알림센터의 리다이렉팅관련 부분을 예외처리 해줘야 할 것 같은데... 사실 다른 부분에서는 다들 잘쓰고 계시거든요...

**Comment by ppleo** [comment]
죄송합니다. 댓글알림입니다.

**Comment by qw5414** [comment]
기존부터 있던 현상인거죠?
