### ISSUE TITLE
@ 으로 멘션을 줬을때 해당 문구를 bold 처리 하는게 좋을거 같습니다.

### ISSUE THREAD

**Issue by hjhj3686** [xe-public/xe-module-ncenterlite#87]
가능하면 깃헙처럼 눌렀을때 프로필 페이지가 보여도 좋겠으나

일단은 강조 처리나 색등을 부여하여 본문 내용과 멘션을 구별하는게 좋을거 같습니다.

직접 해서 PR 해보려고 했는데 어렵네요 ㅜㅜ.

**Comment by qw5414** [comment]
알림센터에서 구현을 재대로 할 수 잇는 사항이 아닌 것 같습니다. 죄송합니다.
