### ISSUE TITLE
게시물 검색시 해당 키워드로 검색하면 글에서 에디터가 보이지 않음.

### ISSUE THREAD

**Issue by hjhj3686** [xe-public/xe-module-ncenterlite#88]
검색시 앞에 ($ 가 들어가면 에디터가 보이지 않습니다.

($docu 로 검색을 돌려서 게시글에 들어갔는데 해당 게시글에서 에디터가 보이지 않네요

그래서 실험을 해봤더니 저 문구가 들어가면 그런걸 보아서 필터링을 해야 될거 같네요.

@YJSoft 님이 알림센터쪽 문제라고 하셔서 이쪽으로 이슈 이동합니다.

(테스트를 공홈에서 했는데 공홈에서도 알림센터를 사용하기 때문에 차마 알림센터의 문제라곤 생각 못했습니다)

https://github.com/xpressengine/xe-core/issues/1653

**Comment by qw5414** [comment]
문제재연이 되지 않는데.. 어떻게 해야하나요?

**Comment by misol** [comment]
($docu 로 검색시 본문 아래 달린 댓글 에디터가 나타나지 않습니다.

IE11 개발자 도구로 살펴보면 SCRIPT5020: 정규식에 ')'가 필요합니다. ncenterlite.js (31,4) 라는 메시지가 나타납니다.

**Comment by qw5414** [comment]
#90 완료.
