### ISSUE TITLE
다국어 처리가 제대로 안되어 있습니다.

### ISSUE THREAD

**Issue by misol** [xe-public/xe-module-ncenterlite#89]
코드에 한국어로 메시지를 입력해 둔 것이 많습니다. 다국어 지원을 하면 좋지 않을까요?

알림을 받는 사용자의 언어에 맞추어 알람을 주는 것에 대해 어떻게 생각하시는지요?

괜찮다면 PR 만들어 넣어보겠습니다.

**Comment by qw5414** [comment]
네 괜찮아요.

**Comment by qw5414** [comment]
`ncenterlite.admin.controller` 70번째줄 `$args->target_summary = '[*] 시험용 알림입니다' . rand();`

**Comment by misol** [comment]
@qw5414 헐.. 아직 많이 남았네요 ㅠㅠ

**Comment by qw5414** [comment]
@misol 추가로 천천히 보내주십시오 ㅎ

**Comment by qw5414** [comment]
@misol ncenterlite.controller.php
`$pos = strpos($item, '님');`
이 부분에서 "님"도 바뀌어야 할 것 같아요 .

**Comment by misol** [comment]
@qw5414 영어로 "님"에 해당되는게 어떤게 있는지 모르겠어요!
한국어 말고는 필요 없을거 같기도 해요

**Comment by qw5414** [comment]
sir?
ㅋㅋㅋ

**Comment by qw5414** [comment]
@misol 나머지는 제가 점검 해보고 적용해보도록 하겠습니다 :) 수고 하셨습니다 :+1:
