### ISSUE TITLE
NotifyType 기능이 동작하지않습니다.

### ISSUE THREAD

**Issue by CONORY** [xe-public/xe-module-ncenterlite#97]
NotifyType 이 기능은 현재 알림센터에 있지만 아무도 쓰지않는(어쩌면 알지못하는) 기능이 되버렸습니다. 이 기능은 모듈을 위한 기능같습니다. 타모듈에서 다른 메세지로 알림을 칠 수 있는 기능으로 파악됩니다.

사용예로 경험치 모듈을 개발중인데.. 레벨업이 되면 알림센터를 통해서 알림을 칠 수 있도록 만드는 중입니다. 알림센터가 메세지가 딱 정해져있어서 레벨업 메세지를 주는 게 불가능해보였지만, 다행히 NotifyType 기능을 쓰면 가능해보였습니다.

하지만, NotifyType 기능이 방치된 탓에 사용하려면 수정이 필요합니다.

ncenterlite.model.php
38줄 $args->notify_type_srl = $notify_srl;
42줄 return $output;

queries/insertNotifyType.xml
3줄 \<table name="ncenterlite_notify_type" /\>

각 줄을 코드를 위의 코드로 변경해주세요.

queries/insertNotify.xml
\<column name="notify_type" var="notify_type" /\>

\<columns\>안에 넣어주세요.

ncenterlite.admin.model.php 파일 82줄

			if($v->type=='U')
			{
				$oNcenterliteModel = getModel('ncenterlite');
				$str = $oNcenterliteModel->getNotifyTypeString($v->notify_type,unserialize($v->target_body));
			}

코드추가..

**Comment by misol** [comment]
알려주셔서 감사합니다.

**Comment by qw5414** [comment]
@YJSoft 이거 확인해보시고 기능에 대한 설명을해주셔야..

**Comment by qw5414** [comment]
`ncenterlite.admin.model.php `파일의 82번째줄이 스위치문인데, 그 스위치문 다음에 바로 넣는게 맞죠?
(현재 알림센터 코어기준 스위치문입니다.)

**Comment by CONORY** [comment]
@qw5414 네.. 알맞게 수정하셨어요.

**Comment by qw5414** [comment]
@misol 빨리 처리 하고 릴리즈 해야할거같아서 가로챘습니다. 죄송.
