### ISSUE TITLE
XE 1.8.12 CSRF 방어 패치 이후 알림창에서 이동이 불가능함

### ISSUE THREAD

**Issue by swccsproj** [xe-public/xe-module-ncenterlite#98]
"잘못된 요청" 에러가 뜨면서 접근이 불가능해짐.

**Comment by swccsproj** [comment]
conf/module.xml 의 procNcenterliteRedirect 에 method="GET|POST" 조건을 추가하면 되는 것 같습니다.

**Comment by qw5414** [comment]
#99 Fixed
